### ISSUE TITLE
Fail to update addon 

### ISSUE THREAD

**Issue by creativetags** [VictoriaMetrics-Community/homeassistant-addon-victoriametrics#41]
![IMG_4200](https://github.com/fuslwusl/homeassistant-addon-victoriametrics/assets/24856/139f0547-c3fb-43cc-ba95-5184e5062758)

**Comment by denisgolius** [comment]
> ![IMG_4200](https://private-user-images.githubusercontent.com/24856/316299496-139f0547-c3fb-43cc-ba95-5184e5062758.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzUxMDIsIm5iZiI6MTcxMTI3NDgwMiwicGF0aCI6Ii8yNDg1Ni8zMTYyOTk0OTYtMTM5ZjA1NDctYzNmYi00M2NjLWJhOTUtNTE4NGU1MDYyNzU4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMDA2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjhiOTE3ZDEzMTA0NmMzOTgyMmE5Zjg0NWY0ZGUwZTJhNGVhMjBjZTFlMTJlNmM3YmI1OTI1M2YzNDJmMGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bbaf5cZuliPeVXHCwYYuxT5GzCoW7wWQ8wFMffVpmCs)

Hey @creativetags , could you please share more information about the device which you are using for home-assistant?
For now it looks like https://github.com/fuslwusl/homeassistant-addon-victoriametrics don't support your device architecture. I would be great if you run `uname -a` from terminal share the output of this command.

**Comment by creativetags** [comment]
It’s a raspberry pi 4

**Comment by denisgolius** [comment]
> It’s a raspberry pi 4

What OS you run on raspberry? There is some different behavior with `uname -m` output for example on debian or arch linux. Please share the output:
- from `uname -m`
- from `uname -a`
- from `lscpu`

Thanks!

**Comment by creativetags** [comment]
aarch64
Linux a0d7b954-ssh 6.1.73-haos-raspi #1 SMP PREEMPT Wed Mar 13 12:10:55 UTC 2024 aarch64 Linux

lscpu is not installed. It's the standard Home Assistant install from https://www.home-assistant.io/installation/raspberrypi The only non-standard thing is I've moved data to a USB memory stick via Settings > System > Storage > Three Dots Menu >  Move datadisk

**Comment by creativetags** [comment]
Still an issue with version 1.9.2

Error updating Victoria Metrics: The command '/bin/ash -o pipefail -c /bin/bash -c 'set -ex &&     ARCH=$(uname -m) &&     if [ "$ARCH" == "x86_64" ]; then         wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/$VERSION/victoria-metrics-linux-amd64-$VERSION.tar.gz -qO- | tar xvz -C /;     elif [[ "$ARCH" == "arm"* ]]; then         wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/$VERSION/victoria-metrics-linux-arm-$VERSION.tar.gz -qO- | tar xvz -C /;     elif [ "$ARCH" == "aarch64" ]; then         wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/$VERSION/victoria-metrics-linux-arm64-$VERSION.tar.gz -qO- | tar xvz -C /;     else         echo "Unsupported architecture $ARCH";         return -1;     fi'' returned a non-zero code: 1

**Comment by denisgolius** [comment]
Hey @creativetags @robvolgers , please share the output of `uname -m` and `echo $SHELL`from your devices.

**Comment by creativetags** [comment]
aarch64
/bin/sh

**Comment by robvolgers** [comment]
aarch64
/bin/sh

**Comment by robvolgers** [comment]
Update: Home Assistant crashed  shortly after. After a new clean install + recent backup I could update Victoria Metrics with no problem.

**Comment by denisgolius** [comment]
I am closing this ticket as there has been no feedback for two months, so I believe the problem has been resolved. If the problem occurs again, please reopen the ticket.

**Comment by creativetags** [comment]
Sorry for not replying. I have now tested and it's working well thanks.
